# https://docs.docker.com/engine/reference/commandline/compose_up
version: "3.9"

services:
  postgresql:
    image: postgres:16
    container_name: kambing-cup-postgres
    hostname: database
    restart: no
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - ${DB_HOST}:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

volumes:
  postgres_data:
